# ============================================================================
# PNPM Workspace 配置文件
# 定义 monorepo 中所有包的位置
# ============================================================================

packages:
  # 核心库包 - 所有以 @quant 为前缀的内部包
  - 'packages/*'

  # 应用程序包 - 实际运行的应用
  - 'apps/*'
